alter table GROUPS_INTER_CHANNEL add FOREIGN KEY (group_name) REFERENCES GROUPS(NAME);
alter table GROUPS_INTER_CHANNEL add FOREIGN KEY (channel_link) REFERENCES CHANNEL(LINK);

alter table ITEM add FOREIGN KEY (ENCLOSUREKEY) REFERENCES ENCLOSURE(LINK);
alter table ITEM add FOREIGN KEY (CHANNELKEY) REFERENCES CHANNEL(LINK);

alter table DOWNLOADS add FOREIGN KEY (ITEMKEY) REFERENCES ITEM(GUID);