
package de.berlios.vch.parser.n24.tvnext;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TvNextCorePortType", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TvNextCorePortType {


    /**
     * 
     * @param limit
     * @param ressortId
     * @param offset
     * @return
     *     returns de.berlios.vch.parser.n24.tvnext.ArrayOfTvNextClip
     */
    @WebMethod(action = "getClipsByRessortId")
    @WebResult(name = "getClipsByRessortIdResult", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
    @RequestWrapper(localName = "getClipsByRessortId", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetClipsByRessortId")
    @ResponseWrapper(localName = "getClipsByRessortIdResponse", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetClipsByRessortIdResponse")
    public ArrayOfTvNextClip getClipsByRessortId(
        @WebParam(name = "ressortId", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        int ressortId,
        @WebParam(name = "offset", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        Integer offset,
        @WebParam(name = "limit", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        Integer limit);

    /**
     * 
     * @param ressortId
     * @return
     *     returns int
     */
    @WebMethod(action = "getClipCountByRessortId")
    @WebResult(name = "getClipCountByRessortIdResult", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
    @RequestWrapper(localName = "getClipCountByRessortId", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetClipCountByRessortId")
    @ResponseWrapper(localName = "getClipCountByRessortIdResponse", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetClipCountByRessortIdResponse")
    public int getClipCountByRessortId(
        @WebParam(name = "ressortId", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        int ressortId);

    /**
     * 
     * @param idList
     * @return
     *     returns de.berlios.vch.parser.n24.tvnext.ArrayOfTvNextClip
     */
    @WebMethod(action = "getClipsByIdList")
    @WebResult(name = "getClipsByIdListResult", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
    @RequestWrapper(localName = "getClipsByIdList", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetClipsByIdList")
    @ResponseWrapper(localName = "getClipsByIdListResponse", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetClipsByIdListResponse")
    public ArrayOfTvNextClip getClipsByIdList(
        @WebParam(name = "idList", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        ArrayOfint idList);

    /**
     * 
     * @param dummy
     * @return
     *     returns de.berlios.vch.parser.n24.tvnext.ArrayOfN24Ressort
     */
    @WebMethod(action = "getRessorts")
    @WebResult(name = "getRessortsResult", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
    @RequestWrapper(localName = "getRessorts", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetRessorts")
    @ResponseWrapper(localName = "getRessortsResponse", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetRessortsResponse")
    public ArrayOfN24Ressort getRessorts(
        @WebParam(name = "dummy", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        Integer dummy);

    /**
     * 
     * @param isin
     * @return
     *     returns de.berlios.vch.parser.n24.tvnext.ArrayOfTvNextClip
     */
    @WebMethod(action = "getClipsByIsin")
    @WebResult(name = "getClipsByIsinResult", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
    @RequestWrapper(localName = "getClipsByIsin", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetClipsByIsin")
    @ResponseWrapper(localName = "getClipsByIsinResponse", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetClipsByIsinResponse")
    public ArrayOfTvNextClip getClipsByIsin(
        @WebParam(name = "isin", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        String isin);

    /**
     * 
     * @param limit
     * @param offset
     * @return
     *     returns de.berlios.vch.parser.n24.tvnext.ArrayOfTvNextClip
     */
    @WebMethod(action = "getNewestClips")
    @WebResult(name = "getNewestClipsResult", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
    @RequestWrapper(localName = "getNewestClips", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetNewestClips")
    @ResponseWrapper(localName = "getNewestClipsResponse", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetNewestClipsResponse")
    public ArrayOfTvNextClip getNewestClips(
        @WebParam(name = "offset", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        Integer offset,
        @WebParam(name = "limit", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        Integer limit);

    /**
     * 
     * @param limit
     * @param searchPhrase
     * @param offset
     * @return
     *     returns de.berlios.vch.parser.n24.tvnext.ArrayOfTvNextClip
     */
    @WebMethod(action = "search")
    @WebResult(name = "searchResult", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
    @RequestWrapper(localName = "search", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.SearchResponse")
    public ArrayOfTvNextClip search(
        @WebParam(name = "searchPhrase", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        String searchPhrase,
        @WebParam(name = "offset", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        Integer offset,
        @WebParam(name = "limit", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        Integer limit);

    /**
     * 
     * @param name
     * @return
     *     returns de.berlios.vch.parser.n24.tvnext.ArrayOfN24NavigationStructure
     */
    @WebMethod(action = "getNavigationTreeByNodeName")
    @WebResult(name = "getNavigationTreeByNodeNameResult", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
    @RequestWrapper(localName = "getNavigationTreeByNodeName", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetNavigationTreeByNodeName")
    @ResponseWrapper(localName = "getNavigationTreeByNodeNameResponse", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/", className = "de.berlios.vch.parser.n24.tvnext.GetNavigationTreeByNodeNameResponse")
    public ArrayOfN24NavigationStructure getNavigationTreeByNodeName(
        @WebParam(name = "name", targetNamespace = "http://schemas.exozet.com/tvnext/services/core/")
        String name);

}
